### ISSUE TITLE
[TODO] 2021년 1월 4주 ~ 2월 1주

### ISSUE THREAD

**Issue by ci-ch3224** [ci-ch3224/contract-proto#3]
- [x] 팝업 레이아웃 정리 - 태현
- [x] 페이징 처리 - 태경
- [x] 완료된 템플릿 보기 - 태경
- [ ] 팝업 완성도 작업 (토스트 메세지, 내용 refresh 등) - 창호
- [x] 계약서 특화 (용역계약서) - 창호
- [x] 메뉴 네비게이션을 상단으로 이동 - 태현
- [ ] "을" 서명 받는 화면 - 태현
- [x] 등록자, 수정일 넣기 - 태경
- [x] 홈 화면 작성 - 태현
